export const POSTS_GET_REQUEST = 'POSTS_GET_REQUEST';
export const POSTS_GET_SUCCESS = 'POSTS_GET_SUCCESS';
export const POSTS_STORE_REQUEST = 'POSTS_STORE_REQUEST';
export const POSTS_UPDATE_REQUEST = 'POSTS_UPDATE_REQUEST';
export const POSTS_UPDATE_SUCCESS = 'POSTS_UPDATE_SUCCESS';
